/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:08b0d3c6-989a-463f-aff0-c233b39a2441",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_rAVxrcryF",
    "aws_user_pools_web_client_id": "59i6660g8e4tf7iau28mn62u4f",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4nscss2ovfebhcyp37fbvxt4oa.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
